ignored_colors = [
    #000000, # filter black, DO NOT USE "#"!!!
]
allowed_colors = [
    #000000, # allow black, DO NOT USE "#"!!!
    "FF4500",
    "FFA800",
    "FFD635",
    "00A368",
    "7EED56",
    "2450A4",
    "3690EA",
    "51E9F4",
    "811E9F",
    "B44AC0",
    "FF99AA",
    "9C6926",
    "000000",
    "898D90",
    "D4D7D9",
    "FFFFFF"
]
width = 2000
height = 1000
add-x = 1000
add-y = 500

default_prio = 120 # priority: higher number = higher chance of being placed


# example:
# [[structure]]
# name = "flagge-ost"
# file = "flagge-ost.png"
# priority_file = "flagge-ost_prio.png"
# startx = 1332
# starty = 1122
# priority = 127
# overlay_only = false

[[structure]]
name = "background"
file = "background.png"
startx = 146
starty = -368
priority = 1

# [[structure]]
# name = "lightmotiv"
# file = "Lightmotiv.png"
# startx = -720
# starty = -329
# priority = 127

[[structure]]
name = "fin"
file = "fin.png"
startx = 147
starty = -367
priority = 127

[[structure]]
name = "lightmotiv logo"
file = "Lightmotiv_logo.png"
startx = 161
starty = -356
priority = 127

[[structure]]
name = "Mona"
file = "mona-eule.png"
startx = 150
starty = -352
priority = 127

[[structure]]
name = "peachy"
file = "peachy.png"
startx = 162
starty = -367
priority = 127

[[structure]]
name = "luna-melon-maaku"
file = "luna-melon-maaku.png"
startx = 177
starty = -356
priority = 127

# [[structure]]
# name = "jinja logo"
# file = "JinjaPixelLogo.png"
# startx = 0
# starty = 0
# priority = 127

[[structure]]
name = "hase"
file = "hase.png"
startx = 202
starty = -341
priority = 127