ignored_colors = []
allowed_colors = ["6D001A", "BE0039", "FF4500", "FFA800", "FFD635", "FFF8B8", "00A368", "00CC78", "7EED56", "00756F", "009EAA", "00CCC0", "2450A4", "3690EA", "51E9F4", "493AC1", "6A5CFF", "94B3FF", "811E9F", "B44AC0", "E4ABFF", "DE107F", "FF3881", "FF99AA", "6D482F", "9C6926", "FFB470", "000000", "515252", "898D90", "D4D7D9", "FFFFFF"]
width = 3000
height = 2000
add-x = 1500
add-y = 1000
default_prio = 120


# example:
# [[structure]]
# name = "flagge-ost"
# file = "flagge-ost.png"
# priority_file = "flagge-ost_prio.png"
# startx = 1332
# starty = 1122
# priority = 127
# overlay_only = false

[[structure]]
name = "lightmotiv logo"
file = "Lightmotiv_logo.png"
startx = -558
starty = -315
priority = 127

[[structure]]
name = "neues design"
file = "neues_design.png"
startx = 146
starty = -368
priority = 127

[[structure]]
name = "Bif"
file = "PixelBif.png"
startx = 1052
starty = 225
priority = 127

[[structure]]
name = "Herz"
file = "herz.png"
startx = -557
starty = -296
priority = 128